'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contact
    Public Property ContactID As Integer
    Public Property ClientID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property EmailId As String
    Public Property Phoneno As String
    Public Property Age As Integer

    Public Overridable Property Client As Client

End Class
